### ISSUE TITLE
yii Failed to instantiate component

### ISSUE THREAD

**Issue by zhangqiupeng** [shyevsa/yii2-redis-sentinel#1]
{"status":404,"message":"Failed to instantiate component or class \"\\shyevsa\\redis\\Connection::class\".","data":[]}
![image](https://user-images.githubusercontent.com/54567187/165239115-b09d10b3-dfc3-4c4d-9bcb-b7f7922847c2.png)

**Comment by shyevsa** [comment]
Have you tried to remove the `::class`

it should be either 
```
 'class' => \shyevsa\redis\Connection::class
 ```
 
 or 
 
 ```
  'class' => '\shyevsa\redis\Connection'
  ```

**Comment by zhangqiupeng** [comment]
Sorry, I wrote more quotation marks. I'm careless😅😅😅😅😅
